### ISSUE TITLE
Saving report as text sometimes fails

### ISSUE THREAD

**Issue by gmcgath** [digital-preservation/droid#74] opened 2015-11-02 23:19 UTC
In the GUI version of DROID 6.1.5, if I create a report and then export it, leaving the default format of Text, it goes through the motions of selecting a file, but no file is created. If I change to another format and then back to Text, it works. 

The failure to output is accompanied by a stack dump; here's the beginning of it.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at uk.gov.nationalarchives.droid.gui.report.ExportReportAction.execute(ExportReportAction.java:86)
    at uk.gov.nationalarchives.droid.gui.report.ReportViewFrame.exportButtonActionPerformed(ReportViewFrame.java:244)
    at uk.gov.nationalarchives.droid.gui.report.ReportViewFrame.access$200(ReportViewFrame.java:77)
    at uk.gov.nationalarchives.droid.gui.report.ReportViewFrame$2.actionPerformed(ReportViewFrame.java:178)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6505)

**Comment by snail1966** [comment] 2015-11-04 17:41
Hi Gary,
Would you be able to provide any further information including which report this was, and the circumstances e.g. was it for a single or multiple profiles, did you save them first, were there any filters etc. Also, any other relevant information such as the operating system, Java version etc.  
Thanks, Brian

**Comment by gmcgath** [comment] 2015-11-04 19:00
launch droid.sh
Work with default untitled profile
Add a folder
Click Save and save profile
Click Start and run profile
Define filter: File extension equal to pdf
Click Report, check the saved profile, choose "File count and sizes by mime type", Click "Report on profiles..."
In report, click on "Export"
Navigate to Desktop and name file Problem.txt
Click Save without changing format
Get error described in report

java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

Operating System: OS X Yosemite 10.10.5

**Comment by snail1966** [comment] 2015-11-09 11:33
Thanks for the information Gary, will investigate further and get back to you.
Regards, Brian

**Comment by snail1966** [comment] 2015-11-11 18:57
Hi Gary
Have had an initial look but been unable to reproduce the issue thus far.  We will shortly be carrying out testing for the next release of DROID and will  investigate this issue in more depth as part of that testing process.
Regards, Brian

**Comment by snail1966** [comment] 2016-02-02 14:56
Seems to be a Mac OS X specific issue - null pointer exception in line 85 of ExportReportAction.java.  Needs further investigation but unlikely to make the imminent next release unfortunately.
Regards, Brian

**Comment by paulyoung84** [comment] 2016-08-22 13:11
This issue has been added to the DROID backlog, it will be assigned an appropriate priority but is unlikely to be included in the next release.

**Comment by snail1966** [comment] 2016-11-23 19:10
Apologies that this remains outstanding -  it may be partially fixed in the code at:
https://github.com/snail1966/droid/tree/macOSXreports
This basically adds an "All files" dummy option to the lists of export formats on the Mac - the error is then transferred to this option and the actual export options should work OK.  However, further testing is needed - may only work some of the time depending on e.g. whether there's already been a previous export in this DROID session.

**Comment by rhubner** [comment] 2017-01-27 14:44
![](https://github.trello.services/images/mini-trello-icon.png) [#74 Saving report as text in Mac sometimes fails](https://trello.com/c/eIAad7lV/5-74-saving-report-as-text-in-mac-sometimes-fails)

**Comment by DavidUnderdown** [comment] 2017-05-25 12:57
In test

**Closed** 2017-07-20 11:06 UTC
Labels: bug, test
