### ISSUE TITLE
6.2 Standard Skeleton Suite Testing Match Issues (regression failures) 

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#87] opened 2016-02-19 04:39 UTC
Hi All,

Sorry to possibly be the bearer of bad news here. I've completed regression testing using my skeleton suites: https://github.com/exponential-decay/skeleton-test-suite 

I tested v84, and also v82 with their corresponding signature files. I just happened to have the latter immediately available. 

Importantly, in both we are seeing the same issues.The following files _**are**_ matching in DROID 6.1.5, but _**are not**_ matching in 6.2:

- fmt-357-signature-id-526.3gp
- fmt-86-signature-id-65.pcx
- fmt-87-signature-id-64.pcx
- fmt-88-signature-id-63.pcx
- fmt-89-signature-id-62.pcx
- x-fmt-140-signature-id-623.bw
- x-fmt-270-signature-id-505.bmp
- x-fmt-367-signature-id-627.tga

I can't see why these signatures specifically would be a problem but the skeleton files are accurate to the best of my understanding and verification. Attached to this report is a zip containing just the Skeleton files proving to be problematic, and once I've pressed submit on this issue I'll get to work on releasing the full v84 skeleton suite (standard signatures only) for you to compare against too. 

Other files not matching but are the same in 6.1.5 and 6.2 seem to be related to the interplay of containers and standard signatures, already partially logged here: https://github.com/digital-preservation/droid/issues/19  

There are two sets of problematic objects in the zip - the difference is the bytes that fill the gaps in the signature syntax created by say, {n} syntax where {n} 0x00 bytes may be used. 

The skeleton suite can be configured to modify the filler byte and I've opted for 0x00 in one set, and 0xAB in another set - it is hoped the latter makes it easier to spot the patterns across the bytestream. Both sets of files check out in 6.1.5 but not 6.2.

The only container signatures I've been able to verify are: skeleton-container-suite-20150327 and they look okay. 

**The spreadsheet:**

![image](https://cloud.githubusercontent.com/assets/1880412/13166514/a7cabcc6-d72d-11e5-97df-bde232cf8bd1.png)

**Configurations:**

![6 1 5-settings](https://cloud.githubusercontent.com/assets/1880412/13166567/3a8f3370-d72e-11e5-8f97-b0e29a18aaaf.png)

![6 2-settings](https://cloud.githubusercontent.com/assets/1880412/13166573/3f86b146-d72e-11e5-9016-5c9e8bd07945.png)

**N.B.** It might be a good idea to have a comprehensive suite like the skeleton suite included in DROID unit tests for regression testing like this, and the maintenance should not normally be high because fewer signature definitions are updated than added and the primary purpose is to test the matching engine not the signature definitions specifically, and so can always refer to a static set. There's a comprehensive set available on the link above. The research paper presented at IDCC is also at the link at the very top of this in case it is useful. 

[v84-broken-skeletons.zip](https://github.com/digital-preservation/droid/files/137418/v84-broken-skeletons.zip)

**Comment by snail1966** [comment] 2016-02-19 13:52
OK, currently investigating, possibly the issue is where a signature has 3 or more alternative values e.g. (00|01|02|03). for a single byte.

**Comment by ross-spencer** [comment] 2016-02-21 23:38
Thanks for being able to look into this all so quickly. 

As I mentioned above, I'd create a new suite for your own testing purposes. This is now here: https://github.com/exponential-decay/skeleton-test-suite/releases/tag/skeleton-test-suite-2016-01-21-sig-file-v84 

For a set of container skeletons you will need release v82 as I haven't written a handler for the latest byteseek syntax used for bit fields. I can expedite that work if there is an interest. 

For the processing engine alone, something like the v84 set above should be adequate for inclusion in the DROID unit-test package.

**Comment by snail1966** [comment] 2016-02-22 11:58
Thanks for the test suite Ross - I believe this issue is now resolved but would like to do more in depth testing before releasing an update.

**Comment by snail1966** [comment] 2016-03-04 16:01
This should now be fixed in Release candidate 6.2.1, now at: https://oss.sonatype.org/service/local/repositories/ukgovnationalarchives-1022/content/uk/gov/nationalarchives/droid-binary/6.2.1/droid-binary-6.2.1-bin.zip  This should be released formally in the next few days. Regards, Brian

**Comment by ross-spencer** [comment] 2016-03-08 03:30
Hi Brian,

Thanks again. This fix looks good to me also:

![image](https://cloud.githubusercontent.com/assets/1880412/13591190/1cd788d4-e54b-11e5-9977-bc69f94068b1.png)

Ross

**Closed** 2016-09-05 10:04 UTC
