### ISSUE TITLE
OPEN LOCATION OF FILES IN WINDOWS FILE SYSTEM doesn't work on Centos and Raspbian

### ISSUE THREAD

**Issue by jcharlet** [digital-preservation/droid#426] opened 2020-03-18 17:24 UTC

**Comment by sparkhi** [comment] 2020-03-19 16:57
I was unable to reproduce it on CentOS 8 that I have at my disposal. I suspect this is related to not having an application set on the system to browse filesystem. We simply launch the filesystem URI and let the system handle the application it would use to launch the URI. Trying to get to the bottom of this, I extracted relevant code and ran it on that system with help from @paulyoung84 and saw the following stack trace 

```
java.io.IOException: Failed t show URI:file:/home/pi/
at sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:121)
at sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:84)
at java.awt.Desktop.open(Desktop.java:272)
```

I think this is related to system setting specific to that system, not a bug in Droid

**Comment by jcharlet** [comment] 2020-03-20 14:25
mmh what shall we do about this then? think we should close it?

**Comment by sparkhi** [comment] 2020-03-20 14:32
I think we should close it. We may see this happen on other systems too, but we at least have an idea of the reason. It would have been nice to try and alter the mimecache settings to pinpoint but I don't have access to those machines right now. I think we should close this.

**Closed** 2020-03-20 15:42 UTC
Labels: bug
