### ISSUE TITLE
Audit of inconsistencies between CLI and GUI on functionalities and code

### ISSUE THREAD

**Issue by jcharlet** [digital-preservation/droid#469] opened 2020-06-10 10:25 UTC
- Audit CLI functionality vs GUI
check if funcs missing on one side or the other

- Audit duplicated code between CLI and GUI
Audit to determine duplicated code with goal to unify/share codebase
all duplicated code might have offer the same functionalities but have different behaviour
-- run code duplication tool 
-- report different modules/packages/functionalities duplicated 
-- evaluate how much duplication vs reimplementation
-- decide whether which module we will choose as reference (between gui and cli) when we will start refactoring (move packages to common modules, reuse in both cli and gui)

spreadsheet comparison features: see GUI/CLI tabs in 
https://docs.google.com/spreadsheets/d/185SLvA3-mtkkjhHx2iR-G3b6GM-sUK0H4aPOvl_JvH0

summary of functionalities in mindmap
https://www.mindomo.com/mindmap/b5d94a7f8e274adbb7a7dbab78f8fa7b

**Comment by nishihatapalmer** [comment] 2021-02-03 08:46
This is almost a duplicate of another issue.  I'm working on making the command line use the same code as the GUI for archive processing and signature identification.  See: https://github.com/nishihatapalmer/droid/tree/NoDatabaseProfiling

**Comment by rhubner** [comment] 2022-03-24 13:05
I run _Duplicate code fragment_ tool in IntelliJ and didn't find any duplicate code. All have been fixed with #743

**Closed by rhubner** 2022-03-24 13:05 UTC
Labels: HIGH
