### ISSUE TITLE
unexpected feedback on signature update in CLI

### ISSUE THREAD

**Issue by jcharlet** [digital-preservation/droid#413] opened 2020-03-11 15:48 UTC
identified by @paulyoung84 

some odd behavior again in signature updates in cmd line, when i remove latest signature update '96' and tell it to check for signature updates it tells me there aren't any but in the .droid6 folder it downloads 96. It does the same if i tell it to download the latest signature file, tells me there isn't one but downloads it anyway.

It actually seems to download latest signature file if i run any cmd line query. Have tried changing default sig to 91 but get same behavior. Haven't seen this behavior in 6.4. Doesn't do this in the GUI all works as expected.

have tried in win 10 and Raspbian

**Comment by sparkhi** [comment] 2020-03-13 12:19
I've investigated and I can confirm that this is not a bug. The default signature file is available in the droid codebase for each version. At this moment, the default signature file in droid (v96) and the latest file available in pronom service is same, hence there is no update available.
For v6.4, the default signature file was v91 and the latest available in pronom service is v96 hence it reports that a newer file is available.

This mode of working (i.e. having a default available with the application) is beneficial for any users who may not have access to the internet when droid is run. 

This is not a bug, closing it without any code change.

**Closed by sparkhi** 2020-03-13 12:19 UTC
Labels: bug
