### ISSUE TITLE
Wrong encoding in XML reports (Windows)

### ISSUE THREAD

**Issue by marhop** [digital-preservation/droid#116] opened 2016-10-13 11:47 UTC
The XML files DROID writes when creating a report claim to be UTF-8 encoded, having `encoding="UTF-8"` in the XML header. However, when reporting on a profile with a name that contains characters outside the ASCII range, the profile name (e.g., in the report file's element `/Report/Profiles/Profile/Name`) is _not_ encoded as UTF-8. It rather looks like ISO 8859-1 (Latin-1) encoding. As a weird side effect, the DROID GUI will not open the report window in this case.

This happens only on Windows! On Linux, the whole report XML file (including the funny profile name) is encoded correctly as UTF-8.

To reproduce:
1. Start DROID (GUI), add some files and save the profile using a file name that contains characters outside the ASCII range, like german umlauts ä, ö, ü.
2. Run an analysis. Everything should work fine.
3. Create a report (any template). A report XML file is created in the `C:\Users\Me\.droid6\tmp` directory, but the usual report windows does _not_ open. (DROID continues to work normally afterwards.) Looking at the report XML file you will find the wrong encoding.

Example: Say the profile name contains the character `ü`. In the report XML file, it will be encoded as `FC` (hex) instead of the correct UTF-8 byte stream `C3BC` (hex).

Tested configuration: Windows 7 (german), Java 8u101, DROID 6.2.1

**Comment by adamretter** [comment] 2016-10-13 11:55
@marhop I think I know what this is, just to check, on your Linux system where it works what is the value of your `LANG` environment variable?

**Comment by marhop** [comment] 2016-10-13 11:59
@adamretter `de_DE.UTF-8`

**Comment by adamretter** [comment] 2016-10-13 13:20
@marhop Okay as I expected, your Linux system uses a `UTF-8` encoding as its default character set, that is not the case on Windows.

So I suspect that in droid somewhere there is a conversion from `byte[]` to `String` without specifying an explicit UTF-8 character encoding (in which case it will use the system default I believe). Perhaps at @snail1966 can help you find that?

**Comment by snail1966** [comment] 2016-10-13 15:35
Thanks  marhop for raising this, and Adam for your input.  It indeed does look as though it may be defaulting to OS default in the absence of a specific character set, will investigate further,
Regards, Brian

**Comment by snail1966** [comment] 2016-11-18 17:18
Confirmed similar behaviour in Windows 7 with GB settings, when running the compiled JAR.  Curiously though, when run in the Intellij IDE the report window does open and the XML is correctly UTF-8 encoded...

**Comment by snail1966** [comment] 2016-11-23 19:02
This issue now appears to be fixed in development.   I also found that there were related issues affecting export of reports from the DROID GUI, and the generation of reports using the command line.  These issues should all now be fixed in the codebase (at my fork at https://github.com/snail1966/droid/tree/report-Xml-Utf-8).  The necessary changes were more wide ranging than initially envisaged, and further testing will be required across various platforms - it is thus not clear just now whether this will be included in the next release expected before Christmas.  

N.B. once this code is deployed to a release, it may also be necessary for existing users to update manually the Web page.html.xsl file under report definitions (or edit the file to include the <meta charset="utf-8"/> in the HTML head) - this is required to ensure the Web page export renders correctly.

However, the following workaround may help in the meantime:- Instead of opening droid.bat, run DROID directly from the command line using java or javaw, and specify the UTF-8 encoding via a flag.  E.g. the following works for me in Powershell (the single quotes are required in Powershell but not cmd):
>java '-Dfile.encoding=UTF-8' -jar .\droid-ui-6.2.1.jar 

Hopefully this is of some help pending the code update. Thanks again marhop for raising this issue, and Adam for your input.
Regards, Brian

**Comment by marhop** [comment] 2016-12-05 15:02
I can confirm that with Brian's workaround (explicitly specifying the encoding when running the JAR file) the report window opens as expected. Thank you!

**Comment by DavidUnderdown** [comment] 2017-03-03 09:39
Fixed by c8809fa and included in [Droid 6.3](https://github.com/digital-preservation/droid/releases/tag/droid-6.3)

**Closed by DavidUnderdown** 2017-03-03 09:39 UTC
Labels: bug
