### ISSUE TITLE
Image scaling issues on high resolution screens or Surface Pro specific?

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#166] opened 2017-06-23 12:29 UTC
I've had a report of a user (Ed Pinsent) on a Win10 Surface Pro tablet that DROID hits image scaling issues. We need to understand whether this is specific to Surface tablets or generally with high res screens and DPI scaling, and deal with accordingly.
Representative screenshots below, used with permission
![appscaling](https://user-images.githubusercontent.com/2189778/27482022-9048664a-5817-11e7-99c3-93c2c1046a90.png)
![appscaling2](https://user-images.githubusercontent.com/2189778/27482023-9057d166-5817-11e7-8fe2-4181d0e9953b.png)

**Comment by alexgreenDP** [comment] 2017-07-03 14:17
This issue has been added to the DROID backlog, it will be assigned an appropriate priority but is unlikely to be included in the next release.

**Comment by alexgreenDP** [comment] 2017-07-03 14:18
Closed in error.

**Comment by jcharlet** [comment] 2019-10-29 11:49
@Dclipsham any idea of the resolution? Can't reproduce on 1920 * 1080

**Comment by Dclipsham** [comment] 2019-10-29 12:08
Afraid not - we weren't able to reproduce. We did have a second report from a user on a 'windows 10 laptop' but they were unable to provide us with further information re model, resolution etc. As unable to reproduce happy for this to pause and reopen if we get further reports.

**Comment by jcharlet** [comment] 2019-10-29 12:28
@Dclipsham could I get a surface pro from support to test on? 
As I said on trello, I have another display issue when building with java11 (but it's not on the exact same part of the interface), I'll be already investigating this one, maybe there is sthing related.

**Comment by jcharlet** [comment] 2019-11-12 17:36
Fixed in PR https://github.com/digital-preservation/droid/pull/289

**Closed by jcharlet** 2019-11-12 17:36 UTC

**Comment by jcharlet** [comment] 2020-01-02 12:53
the following 2 PRs improve the icons which were pixelated when UI is scaled.
