### ISSUE TITLE
DROID not processing all files when using MaxMemory JVM argument

### ISSUE THREAD

**Issue by AnanthNagarajanInfosys** [digital-preservation/droid#67] opened 2015-07-22 09:06 UTC
Hi All,

I am using DROID command line utility for identifying files present in a folder. What I noticed is that when I give MaxMemory JVM argument (java -jar Xmx1024m) to run DROID command-line utility for processing files, DROID was NOT processing ALL files. But when I execute it without providing Xmx1024m, I find that all files are processed. Also, DROID run in UI mode is able to process all files.I have 100 files exactly, each around 100 MB to 300 MB size and the total size is around 20 GB. 

I didn't face this issue earlier when some 500,000 files were processed (with Xmx argument) - but all those files were smaller (in KBs). Do you know if this is something to do with allocating not enough heap space (Xmx argument) for java? I even tried running DROID for this 100-file set with Xmx2048m and Xmx3072m but with no success - not all files were processed. Strange thing is, DROID is not showing any errors or logs and exits normally. 

NOTE: I get the list of processed files by exporting the profile to csv. Even when I look at the profile using UI, I see only subset and NOT all 100 files.

Thanks,

**Comment by snail1966** [comment] 2015-07-22 16:20
Hi,
This is interesting in as much as the default setting for -Xmx is 512 MB. This is specified in the droid.bat file (Windows) or droid.sh file (Linux/Mac OS X).  So (assuming you haven't changed this) it appears in this case that assigning more - rather than less - heap memory is leading to the files being skipped. A similar issue has been raised before, with the possibiity that files were being skipped due to insufficient heap memory. However, on looking into this I could not find defintive evidence that this was actually happening.  I experimented with lowering the heap size setting to see if I could force any change in behaviour.  This did lead to heap space out of memory errors occuring - though these were logged and again there was no evidence of files being silently skipped.

Could you please provide details of the operating system and java version you're using.  Also, any information about the types and whether the same ones are skipped each time might be helpful.
Thanks, Brian

**Comment by AnanthNagarajanInfosys** [comment] 2015-07-24 04:52
Hi @snail1966 ,
We didn't use DROID.bat file. But instead created our own, nothing much in it but just: "java -Xms256m -Xmx1024m-jar <DROID JAR> <DROID Parameters with Profile details> and some other contents specific to our task. We confirmed that the files that are skipped were not the same, they vary. 

Given below are the details of the system we use:
OS – Windows Server 2008 R2 Standard, Java 1.6. DROID 6.1.5.

If this helps, when processing these 100 files, almost every time we found that JCONSOLE was disconnected saying the job had "ended" even though the DROID job was still running (and with same process ID). Also, sometimes we were able to re-connect JCONSOLE to the same job (same process ID) and sometimes we were not able to.

Thanks,

**Comment by snail1966** [comment] 2015-07-28 08:44
Hi,
Thanks for the info. Could you please post the full output from java -version.
Regards, Brian

**Comment by AnanthNagarajanInfosys** [comment] 2015-07-29 11:59
Hi Brian @snail1966,

Here are the details.. Sorry for the delay!
---------------------------------------------------------------------------------------------------------
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
---------------------------------------------------------------------------------------------------------

**Comment by ross-spencer** [comment] 2015-07-30 01:27
I reported a similar issue in the droid-list mailing list, this might provide clues for that. https://groups.google.com/forum/#!topic/droid-list/-QKY89XDNtQ 

As I understand, the problem is yet to be solved.

**Comment by snail1966** [comment] 2015-07-31 10:30
Hi Ananth
Thanks for the update, as mentioned above I did look into this previously using a smaller heap size but couldn't get the behaviour to occur.  However, we plan to revisit this as part of the testing programme for the next release, which should be out later this year.
Regards, Brian

**Comment by AnanthNagarajanInfosys** [comment] 2015-08-03 04:45
Thank you Brian for letting our team know.

Regards,
Ananth Nagarajan.
91 4447478794.

**Comment by snail1966** [comment] 2015-12-18 10:37
Have tried the current release candidate (https://github.com/snail1966/droid/tree/sha1) over a collection of around 45,000 files using the command line "no profile" (-Nr) syntax.  Tried with default settings and also -Xmx 1024m, 100m and 50m.  No errors or differences in the number of files processed were encountered.  Will run some further tests.
Regards, Brian

**Comment by AnanthNagarajanInfosys** [comment] 2015-12-18 10:52
Hi Brian, @snail1966 ,

Sorry, I think I didn't tell you earlier that we did NOT use -Nr (no profile). We used values like below:

java <minMem> <maxMem> -cp <classPath>-jar <droid.jar> -R -a <inputFolder> -p <profile>.

And as I said, the file size was little huge - 100 - 300MB. 

Thanks,

**Comment by snail1966** [comment] 2015-12-18 11:06
Hi Ananth
Thanks for the update - do plan to test profile mode as well, and with more files.  The actual processing in command line profile mode uses the same underlying code as the GUI, so I'd expect both to be affected if the issue arises.  There are a number of changes in this version to optimise memory usage, which will hopefully help us avoid some the issues that may have occurred in the past.
Regards, Brian

**Comment by snail1966** [comment] 2016-01-06 14:11
After some further testing I was able to reproduce the skipping of files when running with a low heap size (-Xmx100m).  All the files skipped were PowerPoint OLE2 containers (.ppt) files, though it could potentially affect other OLE2 containers.  This should now be fixed in the latest release candidate (https://github.com/snail1966/droid/tree/ole2FileSkippingFix) which is currently being tested.  Any processing errors encountered are logged with a message in the format:
"No reader was obtained for [filename]. This may be due to low memory conditions. Try running with a larger heap size!"
[Filename] being the full path to the file (although in command line no profile mode the name is not available at this point and therefore a generic message is returned to standard output).

This fix should be in the next release, subject to satisfactory further testing.
Regards, Brian

**Comment by AnanthNagarajanInfosys** [comment] 2016-01-07 05:08
Great news Brian. Happy to see you cracked it !! FYI, we now have heap size of 1GB min and max.

**Comment by DavidUnderdown** [comment] 2016-08-08 10:25
We believe original issue has been resolved as in last comment by snail1966

**Closed by DavidUnderdown** 2016-08-08 10:25 UTC
